// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg30C464yr-OvlouS6-2OHwsyLeE6Z7xw',
    appId: '1:38047632301:web:00122432e8b9f07932af24',
    messagingSenderId: '38047632301',
    projectId: 'hmsappproject',
    authDomain: 'hmsappproject.firebaseapp.com',
    databaseURL: 'https://hmsappproject-default-rtdb.firebaseio.com',
    storageBucket: 'hmsappproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDViK8xNsiiS6nCn6SCQNiGm9_urIu8L7E',
    appId: '1:38047632301:android:6486aed71c26f28732af24',
    messagingSenderId: '38047632301',
    projectId: 'hmsappproject',
    databaseURL: 'https://hmsappproject-default-rtdb.firebaseio.com',
    storageBucket: 'hmsappproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLEcHN9EQPQboP4JSkaKa1HaRw8b6aH8Y',
    appId: '1:38047632301:ios:bea64d74568649dd32af24',
    messagingSenderId: '38047632301',
    projectId: 'hmsappproject',
    databaseURL: 'https://hmsappproject-default-rtdb.firebaseio.com',
    storageBucket: 'hmsappproject.firebasestorage.app',
    iosBundleId: 'com.example.hms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLEcHN9EQPQboP4JSkaKa1HaRw8b6aH8Y',
    appId: '1:38047632301:ios:bea64d74568649dd32af24',
    messagingSenderId: '38047632301',
    projectId: 'hmsappproject',
    databaseURL: 'https://hmsappproject-default-rtdb.firebaseio.com',
    storageBucket: 'hmsappproject.firebasestorage.app',
    iosBundleId: 'com.example.hms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg30C464yr-OvlouS6-2OHwsyLeE6Z7xw',
    appId: '1:38047632301:web:d960539720b96a0532af24',
    messagingSenderId: '38047632301',
    projectId: 'hmsappproject',
    authDomain: 'hmsappproject.firebaseapp.com',
    databaseURL: 'https://hmsappproject-default-rtdb.firebaseio.com',
    storageBucket: 'hmsappproject.firebasestorage.app',
  );
}
